export { default as NavBar } from "./NavBar/NavBar";
export { default as MusicFooter } from "./MusicFooter/MusicFooter";
export { default as ProtectedRoute } from "./ProtectedRoute/ProtectedRoute";
export { default as CardDetail } from "./CardDetail/CardDetail";
export { default as MusicPlayer } from "./MusicPlayer/MusicPlayer";
export { default as MusicDetail } from './MusicDetail/MusicDetail';
export { default as Buscador } from './Buscador/Buscador';
export { default as DevAbout } from "./DevAbout/DevAbout";
export { default as DevelopAbout } from "./DevelopAbout/DevelopAbout";
export {default as LoginRegisterModal } from "./LoginRegisterModal/LoginRegisterModal";
